name: Composite Action
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-13]
        python-version: ['graalpy-24.0.2']
       
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up python
        uses: gowridurgad/sample-python@main
        with:
          python-version: ${{ matrix.python-version }}
