name: Composite Action
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-13, ubuntu-24.04-arm, windows-11-arm ]
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
        exclude:
          - os: windows-11-arm
            python-version: '3.9'
          - os: windows-11-arm
            python-version: '3.10'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up python
        uses: gowridurgad/sample-python@main
        with:
          python-version: ${{ matrix.python-version }}
