name: Test167

on:
  workflow_dispatch:

jobs:
  multi-source-test:
    runs-on: ubuntu-latest

    env:
      NUGET_AUTH_TOKEN: ${{ secrets.TOKEN_GITHUB }}
     

    steps:
      - uses: actions/checkout@v4

      - name: Add NuGet.Config with multiple sources
        run: |
          cat > NuGet.Config <<EOF
          <?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <packageSources>
              <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
              <add key="github" value="https://nuget.pkg.github.com/gowridurgad/index.json" />
            </packageSources>
          </configuration>
          EOF
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
          source-url: https://nuget.pkg.github.com/gowridurgad/index.json
      - name: Remove existing source (if any)
        run: dotnet nuget remove source github || true
      - name: Add GitHub Packages Source
        run: dotnet nuget add source https://api.nuget.org/v3/index.json  --name github --username ${{ github.actor }} --password ${{ secrets.TOKEN_GITHUB }} --store-password-in-clear-text
      - name: Restore NuGet packages
        run: dotnet restore ./MyApp/MyApp.csproj

      # Optionally test a build
      - name: Build
        run: dotnet build
        working-directory: ./MyApp
