name: main
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-13 ]
        
       
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
    
      - name: Set up python
        uses: actions/setup-python@main
        with:
             python-version:  '3.11'
             cache: pip
             cache-dependency-path: temp/requirements.txt
             overwrite: true
      - run: pip install -r temp/requirements.txt
             
             
            
