name: main

on:
  workflow_dispatch:

jobs:
  reproduce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cat temp/requirements.txt
    
      

     

      - uses: gowridurgad/sample-python@main


    
      - run: cat temp/requirements.txt
      - run: pip install -r temp/requirements.txt
      - run: cat temp/requirements.txt
      

            
