name: main
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-13 ]
        
       
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
    
      - name: Set up python
        uses: aparnajyothi-y/setup-python@fix-overwirting
        with:
             python-version:  '3.11'
             overwrite: true
             update-environment: true
             
            
             
            
     

      
      

  
