name: main

on:
  workflow_dispatch:

jobs:
  reproduce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cat pyproject.toml

     

      - uses: gowridurgad/sample-python@main
      - run: cat pyproject.toml


    
    
    
     
      

            
