name: main
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    
        
       
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: cat requirements.txt
    
      - name: Set up python
        uses: gowridurgad/sample-python@main
      - run: cat requirements.txt

      
